# Generated by Django 5.1.2 on 2024-10-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inegi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={},
        ),
        migrations.AddField(
            model_name='estado',
            name='cve_ent',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='nombre_abrev',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='pob_femenina',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='pob_masculina',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='pob_total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estado',
            name='total_viviendas_habitadas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
