# Generated by Django 5.1.2 on 2024-10-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_inegi', '0002_alter_estado_options_estado_cve_ent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asentamiento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={},
        ),
        migrations.AddField(
            model_name='asentamiento',
            name='cve_asen',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='asentamiento',
            name='tipo_asen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='localidad',
            name='altitud',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='localidad',
            name='cve_loc',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='localidad',
            name='latitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='localidad',
            name='longitud',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='localidad',
            name='pob_total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='localidad',
            name='total_viviendas_habitadas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='cve_mun',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='asentamiento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='estado',
            name='cve_ent',
            field=models.CharField(default='00', max_length=2, unique=True),
        ),
    ]
